import pygame
from .type import IconType

class Icons:

	ADD: IconType
	ADD_CIRCLE: IconType
	AMULET: IconType
	ANVIL: IconType
	ARMOR: IconType
	ARROW_DOWN: IconType
	ARROW_LEFT: IconType
	ARROW_RIGHT: IconType
	ARROW_UP: IconType
	ARROW_WEAPON: IconType
	AXE: IconType
	BACK: IconType
	BACKPACK: IconType
	BAG: IconType
	BATTERY: IconType
	BELL: IconType
	BOMB: IconType
	BOOK: IconType
	BOOKMARK: IconType
	BOOTS: IconType
	BOW: IconType
	BRIDGE: IconType
	CAMPFIRE: IconType
	CARDS: IconType
	CASTLE: IconType
	CAVE: IconType
	CHAT: IconType
	CHECK: IconType
	CHECK_CIRCLE: IconType
	CHESS: IconType
	CHEVRON_DOWN: IconType
	CHEVRON_LEFT: IconType
	CHEVRON_RIGHT: IconType
	CHEVRON_UP: IconType
	CLOCK: IconType
	CLOSE: IconType
	CLOUD: IconType
	CLOUD_SAVE: IconType
	COIN: IconType
	COINS: IconType
	COLLAPSE: IconType
	COMPASS: IconType
	CROSSHAIR: IconType
	CROWN: IconType
	DELETE: IconType
	DIAMOND: IconType
	DICE: IconType
	DOOR: IconType
	DOWN: IconType
	DOWNLOAD: IconType
	EARTH: IconType
	EDIT: IconType
	ENERGY: IconType
	EXPAND: IconType
	EYE: IconType
	EYE_OFF: IconType
	FAST_FORWARD: IconType
	FILTER: IconType
	FIRE: IconType
	FLAG: IconType
	FLAG_REPORT: IconType
	FLASK: IconType
	FORWARD: IconType
	GAMEPAD: IconType
	GATE: IconType
	GEM: IconType
	GLOVES: IconType
	GRID: IconType
	GUN: IconType
	HAMMER: IconType
	HEADPHONES: IconType
	HEALTH_BAR: IconType
	HEART: IconType
	HEART_BROKEN: IconType
	HELMET: IconType
	HOME: IconType
	HOURGLASS: IconType
	HOUSE: IconType
	JOYSTICK: IconType
	KEY: IconType
	KEYBOARD: IconType
	LADDER: IconType
	LAYERS: IconType
	LEVEL_UP: IconType
	LIGHTNING: IconType
	LINK: IconType
	LIST: IconType
	LOCK: IconType
	MAIL: IconType
	MANA: IconType
	MAP: IconType
	MEDAL: IconType
	MENU: IconType
	MESSAGE: IconType
	MICROPHONE: IconType
	MOUNTAIN: IconType
	MOUSE_DEVICE: IconType
	PAUSE: IconType
	PIN: IconType
	PLAY: IconType
	PORTAL: IconType
	POTION: IconType
	POWER: IconType
	PUZZLE: IconType
	REFRESH: IconType
	REMOVE: IconType
	REMOVE_CIRCLE: IconType
	REPEAT: IconType
	RESTART: IconType
	REWIND: IconType
	RING: IconType
	SCROLL: IconType
	SEARCH: IconType
	SETTINGS: IconType
	SHARE: IconType
	SHIELD: IconType
	SHIELD_CHECK: IconType
	SHUFFLE: IconType
	SKULL: IconType
	SNOWFLAKE: IconType
	SORT: IconType
	SPEAKER: IconType
	STAR: IconType
	STAR_HALF: IconType
	STOP: IconType
	SWORD: IconType
	SYNC: IconType
	TAG: IconType
	TARGET: IconType
	TENT: IconType
	THUMBS_DOWN: IconType
	THUMBS_UP: IconType
	TIMER: IconType
	TOGGLE_OFF: IconType
	TOGGLE_ON: IconType
	TOWER: IconType
	TREASURE_CHEST: IconType
	TREE: IconType
	TROPHY: IconType
	UNLOCK: IconType
	UP: IconType
	UPLOAD: IconType
	USER: IconType
	USERS: IconType
	VOLUME_MUTE: IconType
	VOLUME_UP: IconType
	WATER_DROP: IconType
	WIFI: IconType
	WIND: IconType
	XP: IconType

	def register(cls, *icons: IconType): ...
	def unregister(cls, *icons: IconType): ...

def code2png(source: str, /, size: int = 32, fill: str = "#FFFFFF", color: str = "#000000") -> pygame.Surface: ...
def icon2png(icon: IconType, /, size: int = 32, fill: str = "#FFFFFF", color: str = "#000000") -> pygame.Surface: ...
def svg2png(path: str, /, size: int = 32) -> pygame.Surface: ...
def url2png(url: str, /, size: int = 32) -> pygame.Surface: ...
