import pygame
from .type import IconType

class Icons:

	ADD: IconType
	ADD_CIRCLE: IconType
	AMULET: IconType
	ANVIL: IconType
	ARMOR: IconType
	ARROW_DOWN: IconType
	ARROW_LEFT: IconType
	ARROW_RIGHT: IconType
	ARROW_UP: IconType
	ARROW_WEAPON: IconType
	AXE: IconType
	BACK: IconType
	BACKPACK: IconType
	BAG: IconType
	BATTERY: IconType
	BELL: IconType
	BOMB: IconType
	BOOK: IconType
	BOOKMARK: IconType
	BOOTS: IconType
	BOW: IconType
	BRIDGE: IconType
	CAMPFIRE: IconType
	CARDS: IconType
	CASTLE: IconType
	CAVE: IconType
	CHAT: IconType
	CHECK: IconType
	CHECK_CIRCLE: IconType
	CHESS: IconType
	CHEVRON_DOWN: IconType
	CHEVRON_LEFT: IconType
	CHEVRON_RIGHT: IconType
	CHEVRON_UP: IconType
	CLOCK: IconType
	CLOSE: IconType
	CLOUD: IconType
	CLOUD_SAVE: IconType
	COIN: IconType
	COINS: IconType
	COLLAPSE: IconType
	COMPASS: IconType
	CROSSHAIR: IconType
	CROWN: IconType
	DELETE: IconType
	DIAMOND: IconType
	DICE: IconType
	DOOR: IconType
	DOWN: IconType
	DOWNLOAD: IconType
	EARTH: IconType
	EDIT: IconType
	ENERGY: IconType
	EXPAND: IconType
	EYE: IconType
	EYE_OFF: IconType
	FAST_FORWARD: IconType
	FILTER: IconType
	FIRE: IconType
	FLAG: IconType
	FLAG_REPORT: IconType
	FLASK: IconType
	FORWARD: IconType
	GAMEPAD: IconType
	GATE: IconType
	GEM: IconType
	GLOVES: IconType
	GRID: IconType
	GUN: IconType
	HAMMER: IconType
	HEADPHONES: IconType
	HEALTH_BAR: IconType
	HEART: IconType
	HEART_BROKEN: IconType
	HELMET: IconType
	HOME: IconType
	HOURGLASS: IconType
	HOUSE: IconType
	JOYSTICK: IconType
	KEY: IconType
	KEYBOARD: IconType
	KEY_0: IconType
	KEY_1: IconType
	KEY_2: IconType
	KEY_3: IconType
	KEY_4: IconType
	KEY_5: IconType
	KEY_6: IconType
	KEY_7: IconType
	KEY_8: IconType
	KEY_9: IconType
	KEY_A: IconType
	KEY_ALT: IconType
	KEY_ARROW_DOWN: IconType
	KEY_ARROW_LEFT: IconType
	KEY_ARROW_RIGHT: IconType
	KEY_ARROW_UP: IconType
	KEY_B: IconType
	KEY_C: IconType
	KEY_CTRL: IconType
	KEY_D: IconType
	KEY_E: IconType
	KEY_ENTER: IconType
	KEY_ESC: IconType
	KEY_F: IconType
	KEY_G: IconType
	KEY_H: IconType
	KEY_I: IconType
	KEY_J: IconType
	KEY_K: IconType
	KEY_L: IconType
	KEY_M: IconType
	KEY_N: IconType
	KEY_O: IconType
	KEY_P: IconType
	KEY_Q: IconType
	KEY_R: IconType
	KEY_S: IconType
	KEY_SHIFT: IconType
	KEY_SPACE: IconType
	KEY_T: IconType
	KEY_TAB: IconType
	KEY_U: IconType
	KEY_V: IconType
	KEY_W: IconType
	KEY_X: IconType
	KEY_Y: IconType
	KEY_Z: IconType
	LADDER: IconType
	LAYERS: IconType
	LEVEL_UP: IconType
	LIGHTNING: IconType
	LINK: IconType
	LIST: IconType
	LOCK: IconType
	MAIL: IconType
	MANA: IconType
	MAP: IconType
	MEDAL: IconType
	MENU: IconType
	MESSAGE: IconType
	MICROPHONE: IconType
	MOUNTAIN: IconType
	MOUSE_DEVICE: IconType
	PAUSE: IconType
	PIN: IconType
	PLAY: IconType
	PORTAL: IconType
	POTION: IconType
	POWER: IconType
	PS_CIRCLE: IconType
	PS_CROSS: IconType
	PS_DPAD: IconType
	PS_HOME: IconType
	PS_L1: IconType
	PS_L2: IconType
	PS_OPTIONS: IconType
	PS_R1: IconType
	PS_R2: IconType
	PS_SHARE: IconType
	PS_SQUARE: IconType
	PS_STICK: IconType
	PS_TOUCHPAD: IconType
	PS_TRIANGLE: IconType
	PUZZLE: IconType
	REFRESH: IconType
	REMOVE: IconType
	REMOVE_CIRCLE: IconType
	REPEAT: IconType
	RESTART: IconType
	REWIND: IconType
	RING: IconType
	SCROLL: IconType
	SEARCH: IconType
	SETTINGS: IconType
	SHARE: IconType
	SHIELD: IconType
	SHIELD_CHECK: IconType
	SHUFFLE: IconType
	SKULL: IconType
	SNOWFLAKE: IconType
	SORT: IconType
	SPEAKER: IconType
	STAR: IconType
	STAR_HALF: IconType
	STOP: IconType
	SWITCH_A: IconType
	SWITCH_B: IconType
	SWITCH_CAPTURE: IconType
	SWITCH_DPAD: IconType
	SWITCH_HOME: IconType
	SWITCH_L: IconType
	SWITCH_MINUS: IconType
	SWITCH_PLUS: IconType
	SWITCH_R: IconType
	SWITCH_STICK: IconType
	SWITCH_X: IconType
	SWITCH_Y: IconType
	SWITCH_ZL: IconType
	SWITCH_ZR: IconType
	SWORD: IconType
	SYNC: IconType
	TAG: IconType
	TARGET: IconType
	TENT: IconType
	THUMBS_DOWN: IconType
	THUMBS_UP: IconType
	TIMER: IconType
	TOGGLE_OFF: IconType
	TOGGLE_ON: IconType
	TOWER: IconType
	TREASURE_CHEST: IconType
	TREE: IconType
	TROPHY: IconType
	UNLOCK: IconType
	UP: IconType
	UPLOAD: IconType
	USER: IconType
	USERS: IconType
	VOLUME_MUTE: IconType
	VOLUME_UP: IconType
	WATER_DROP: IconType
	WIFI: IconType
	WIND: IconType
	XBOX_A: IconType
	XBOX_B: IconType
	XBOX_DPAD: IconType
	XBOX_HOME: IconType
	XBOX_LB: IconType
	XBOX_LT: IconType
	XBOX_MENU: IconType
	XBOX_RB: IconType
	XBOX_RT: IconType
	XBOX_STICK: IconType
	XBOX_VIEW: IconType
	XBOX_X: IconType
	XBOX_Y: IconType
	XP: IconType

	def register(cls, *icons: IconType): ...
	def unregister(cls, *icons: IconType): ...

def code2png(source: str, /, size: int = 32, fill: str = "#FFFFFF", color: str = "#000000") -> pygame.Surface: ...
def icon2png(icon: IconType, /, size: int = 32, fill: str = "#FFFFFF", color: str = "#000000") -> pygame.Surface: ...
def svg2png(path: str, /, size: int = 32) -> pygame.Surface: ...
def url2png(url: str, /, size: int = 32) -> pygame.Surface: ...
